version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1
jobs:
  build:
    docker:
      - image: cimg/php:7.3-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: |
          php --version
          node --version
          java --version
          google-chrome --version
          chromedriver --version

      # Install and run MySQL 8.0.X
      - run:
          name: Install and run MySQL 8.0.X
          command: |
            wget https://repo.mysql.com//mysql-apt-config_0.8.16-1_all.deb
            sudo dpkg -i mysql-apt-config_0.8.16-1_all.deb
            sudo apt update
            sudo apt install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
            mysql --version
            sudo apt install mysql-client
            mysql -uroot --execute="CREATE DATABASE test_varbase808xxc;"

      # Configure and run the virtual display.
      - run:
          name: Configure and run the virtual display
          command: |
            export DISPLAY=:99
            xvfb :99 -ac -screen 0 1366x768x24 &>/dev/null &
            sleep 3

      # Run selenium standalone server.
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-2.53.1.jar -port 4445 > /dev/null 2>&1 &
          background: true

      ## Update the composer
      - run: sudo composer self-update --2
      - run: composer --version

      ## Build with the composer
      - run: composer install --no-interaction -vvv
      - run: git clone --branch 8.x-8.x https://github.com/vardot/varbase.git docroot/profiles/varbase

      ## Update PATH and Define Environment Variable at Runtime.
      - run:
          name: Update PATH to point at the composer bin in the project
          command: |
            echo 'export PATH=/home/circleci/project/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      ## Install with drush.
      - run: cd docroot
      - run: drush site-install varbase --yes --site-name='Test Varbase808xxc' --account-name=webmaster --account-pass=dD.123123ddd --account-mail=webmaster@vardot.com --db-url="mysql://root:@localhost/test_varbase808xxc" varbase_multilingual_configuration.enable_multilingual=true varbase_extra_components.vmi=true varbase_extra_components.varbase_heroslider_media=true varbase_extra_components.varbase_carousels=true varbase_extra_components.varbase_search=true varbase_extra_components.varbase_blog=true varbase_extra_components.varbase_landing=true varbase_extra_components.varbase_auth=true
      - run: drush pm-enable varbase_development --yes
      - run: drush pm-enable varbase_styleguide --yes
      - run: drush pm-enable varbase_media_instagram --yes
      - run: drush pm-enable varbase_media_twitter --yes
      - run: drush pm-enable varbase_api --yes
      - run: drush pm-enable social_auth_google --yes
      - run: drush pm-enable social_auth_facebook --yes
      - run: drush pm-enable social_auth_twitter --yes
      - run: drush pm-enable social_auth_linkedin --yes
      - run: drush pm-enable varbase_content_planner --yes
      - run: drush config-set system.performance css.preprocess 0 --yes
      - run: drush config-set system.performance js.preprocess 0 --yes
      - run: drush config-set system.logging error_level all --yes
      - run: drush cr

      - run: drush runserver --default-server=builtin 8080 &>/dev/null &
      - run: sleep 5

      - run: cd ./profiles/varbase
      - run: behat --strict tests/features/varbase
