version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-apache-stretch-node-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: test_varbase808xxc
      - image: circleci/mysql:8.0.4
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: test_varbase808xxc
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: sudo apt install mysql-client
      - browser-tools/install-browser-tools
      - run: |
          php --version
          node --version
          java --version
          google-chrome --version
          chromedriver --version

      - run: sudo apt update
      - run: sudo apt install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
      - run: sudo -E docker-php-ext-install zip
      - run: sudo -E docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
      - run: sudo -E docker-php-ext-install bcmath pdo_mysql
      - run: sudo -E docker-php-ext-install gd

      # Configure and run the virtual display.
      - run:
          name: Configure and run the virtual display
          command: |
            export DISPLAY=:99
            xvfb :99 -ac -screen 0 1366x768x24 &>/dev/null &
            sleep 3

      # Run selenium standalone server.
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-2.53.1.jar -port 4445 > /dev/null 2>&1 &
          background: true

      ## Update the composer
      - run: sudo composer self-update --2
      - run: composer --version

      ## Build with the composer
      - run: composer install --no-interaction -vvv
      - run: git clone --branch 8.x-8.x https://github.com/vardot/varbase.git docroot/profiles/varbase

      ## Update PATH and Define Environment Variable at Runtime.
      - run:
          name: Update PATH to point at the composer bin in the project
          command: |
            echo 'export PATH=/home/circleci/project/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      ## Install with drush.
      - run: cd docroot
      - run: drush site-install varbase --yes --site-name='Test Varbase808xxc' --account-name=webmaster --account-pass=dD.123123ddd --account-mail=webmaster@vardot.com --db-url="mysql://root:@127.0.0.1/test_varbase808xxc" varbase_multilingual_configuration.enable_multilingual=true varbase_extra_components.vmi=true varbase_extra_components.varbase_heroslider_media=true varbase_extra_components.varbase_carousels=true varbase_extra_components.varbase_search=true varbase_extra_components.varbase_blog=true varbase_extra_components.varbase_landing=true varbase_extra_components.varbase_auth=true
      - run: drush pm-enable varbase_development --yes
      - run: drush pm-enable varbase_styleguide --yes
      - run: drush pm-enable varbase_media_instagram --yes
      - run: drush pm-enable varbase_media_twitter --yes
      - run: drush pm-enable varbase_api --yes
      - run: drush pm-enable social_auth_google --yes
      - run: drush pm-enable social_auth_facebook --yes
      - run: drush pm-enable social_auth_twitter --yes
      - run: drush pm-enable social_auth_linkedin --yes
      - run: drush pm-enable varbase_content_planner --yes
      - run: drush config-set system.performance css.preprocess 0 --yes
      - run: drush config-set system.performance js.preprocess 0 --yes
      - run: drush config-set system.logging error_level all --yes
      - run: drush cr

      - run: drush runserver --default-server=builtin 8080 &>/dev/null &
      - run: sleep 5

      - run: cd ./profiles/varbase
      - run: behat --strict tests/features/varbase
